# Caddy PQ TLS reverse proxy for tunnel-open
# Generated by tunnel-open. Do not edit manually.
#
# Service: ${SERVICE_NAME}
# Upstream: ${UPSTREAM}
# Port: ${LISTEN_PORT}

{
	auto_https off
	admin off
}

${LISTEN_IP}:${LISTEN_PORT} {
	tls ${TLS_CERT} ${TLS_KEY} {
		protocols tls1.3 tls1.3
		curves x25519mlkem768 x25519
	}

	reverse_proxy ${UPSTREAM} {
		header_up Host {http.request.host}
		header_up X-Real-IP {remote_host}
		header_up X-Forwarded-Proto https
	}

	log {
		output stderr
		format json
	}

	header {
		-Server
		X-Content-Type-Options nosniff
		X-Frame-Options DENY
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
		X-Quantum-Safe "true"
	}
}
